import unittest
from pathlib import Path


class MainGuiDocsActionsTests(unittest.TestCase):
    def setUp(self):
        self.main_gui_source = Path("main_gui.py").read_text(encoding="utf-8")
        self.main_window_ui_source = Path("src/auto_write_txt_to_docs/main_window_ui.py").read_text(encoding="utf-8")

    def test_main_gui_contains_doc_creation_and_selection_actions(self):
        self.assertIn("def create_new_google_doc", self.main_gui_source)
        self.assertIn("def select_google_doc", self.main_gui_source)
        self.assertIn("def verify_google_services_before_monitoring", self.main_gui_source)
        self.assertIn("def extract_docs_update_line_count", self.main_gui_source)
        self.assertIn("def toggle_docs_target_lock", self.main_gui_source)
        self.assertIn("def lock_docs_target", self.main_gui_source)
        self.assertIn("def unlock_docs_target", self.main_gui_source)
        self.assertIn("def detect_ui_font_family", self.main_gui_source)
        self.assertIn("def build_ui_font", self.main_gui_source)
        self.assertIn("def present_main_window", self.main_gui_source)
        self.assertIn("def run_startup_prompts", self.main_gui_source)
        self.assertIn("def show_first_run_wizard", self.main_gui_source)
        self.assertIn("DnDCompatibleTk", self.main_gui_source)
        self.assertIn("supports_windows_startup", self.main_gui_source)
        self.assertIn("def start_tray_icon", self.main_gui_source)
        self.assertIn("run_detached", self.main_gui_source)
        self.assertIn('trace_add("write"', self.main_gui_source)
        self.assertIn("def extracted_result_threadsafe", self.main_gui_source)
        self.assertIn("def append_extraction_preview", self.main_gui_source)
        self.assertIn("def process_result_queue", self.main_gui_source)
        self.assertIn("def show_log_popup", self.main_gui_source)
        self.assertIn("def sync_log_popup_content", self.main_gui_source)
        self.assertIn("def close_log_popup", self.main_gui_source)
        self.assertIn("def update_tray_status", self.main_gui_source)
        self.assertIn("def get_tray_state_key", self.main_gui_source)
        self.assertIn("def build_tray_status_icon", self.main_gui_source)
        self.assertIn("def build_tray_menu", self.main_gui_source)
        self.assertIn("def toggle_monitoring_from_tray", self.main_gui_source)
        self.assertIn("def open_docs_in_browser_from_tray", self.main_gui_source)
        self.assertIn("def show_log_popup_from_tray", self.main_gui_source)
        self.assertIn("def setup_watch_folder_drag_and_drop", self.main_gui_source)
        self.assertIn("def on_watch_folder_drop", self.main_gui_source)
        self.assertIn("def update_windows_startup_ui_state", self.main_gui_source)
        self.assertIn("def refresh_windows_startup_setting_from_system", self.main_gui_source)
        self.assertIn("def sync_windows_startup_setting", self.main_gui_source)
        self.assertIn("감시 일시 정지/재개", self.main_gui_source)
        self.assertIn("Docs 웹에서 열기", self.main_gui_source)
        self.assertIn("로그 보기", self.main_gui_source)
        self.assertIn("self.pending_docs_update_line_count", self.main_gui_source)
        self.assertIn("self.show_success_notifications.get()", self.main_gui_source)
        self.assertIn("self.tray_icon.notify(message, title)", self.main_gui_source)
        self.assertIn("create_google_document", self.main_gui_source)
        self.assertIn("list_accessible_google_documents", self.main_gui_source)
        self.assertIn("build_main_window_ui", self.main_gui_source)
        self.assertIn("docs_target_locked", self.main_gui_source)
        self.assertIn("clear_extraction_preview", self.main_gui_source)
        self.assertIn("max_cache_size", self.main_gui_source)
        self.assertIn("parse_max_cache_size", self.main_gui_source)
        self.assertIn("first_run", self.main_gui_source)
        self.assertIn("launch_on_windows_startup", self.main_gui_source)
        self.assertIn("autostart_hint", self.main_gui_source)
        self.assertIn("show_success_notifications", self.main_gui_source)
        self.assertIn("play_event_sounds", self.main_gui_source)
        self.assertIn("self.show_success_notifications.get()", self.main_gui_source)
        self.assertIn("self.play_event_sounds.get()", self.main_gui_source)
        self.assertIn("처음 실행 설정 마법사", self.main_gui_source)
        self.assertIn("Messenger Docs 시작 마법사", self.main_gui_source)
        self.assertIn("tkinterdnd2", self.main_gui_source)
        self.assertIn("Windows 자동 실행", self.main_gui_source)
        self.assertIn("drop_target_register", self.main_gui_source)
        self.assertIn("<<Drop>>", self.main_gui_source)
        self.assertIn("1. 감시 폴더 선택", self.main_gui_source)
        self.assertIn("2. Google Docs 연결", self.main_gui_source)
        self.assertIn("3. 알림 및 마무리", self.main_gui_source)
        self.assertIn("나중에", self.main_gui_source)
        self.assertIn("def configure_log_tags", self.main_gui_source)
        self.assertIn("def get_log_tag_name", self.main_gui_source)
        self.assertIn("def append_log_to_widget", self.main_gui_source)
        self.assertIn("def render_log_lines", self.main_gui_source)
        self.assertIn('self.root.geometry("980x750")', self.main_gui_source)
        self.assertIn('self.root.minsize(980, 750)', self.main_gui_source)
        self.assertIn("⚠️ 기록 불가", self.main_gui_source)
        self.assertIn("오류 상태", self.main_gui_source)
        self.assertIn("preloaded_services", self.main_gui_source)
        self.assertIn("log_success", self.main_gui_source)
        self.assertIn("log_warning", self.main_gui_source)
        self.assertIn("log_error", self.main_gui_source)
        self.assertIn('text="작업 결과 알림 표시"', self.main_window_ui_source)
        self.assertIn('text="작업 결과 효과음 재생"', self.main_window_ui_source)
        self.assertIn('text="새 문서 만들기"', self.main_window_ui_source)
        self.assertIn('text="기존 문서 주소 입력"', self.main_window_ui_source)
        self.assertIn('text="문서 목록"', self.main_window_ui_source)
        self.assertIn('text="문서 경로 확정"', self.main_window_ui_source)
        self.assertIn('text="라인 캐시 크기"', self.main_window_ui_source)
        self.assertIn('text="로그 팝업"', self.main_window_ui_source)


if __name__ == "__main__":
    unittest.main()
