import unittest
from pathlib import Path


class MainWindowUiTests(unittest.TestCase):
    def setUp(self):
        self.source = Path("src/auto_write_txt_to_docs/main_window_ui.py").read_text(encoding="utf-8")

    def test_main_window_ui_exposes_builder_function(self):
        self.assertIn("def build_main_window_ui", self.source)
        self.assertIn("_build_status_panel", self.source)
        self.assertIn("_build_settings_panel", self.source)
        self.assertIn("_build_control_panel", self.source)
        self.assertIn("_build_result_panel", self.source)
        self.assertIn("_build_log_panel", self.source)
        self.assertIn("def _attach_tooltip", self.source)

    def test_main_window_ui_keeps_font_helper_and_workspace_copy(self):
        self.assertIn("def _font", self.source)
        self.assertIn("if family:", self.source)
        self.assertIn("CTkScrollableFrame", self.source)
        self.assertIn('main_frame.pack(padx=14, pady=14, fill="both", expand=True)', self.source)
        self.assertIn('workspace_frame.pack(fill="x", expand=False)', self.source)
        self.assertIn('docs_input_row.pack(fill="x", padx=14, pady=(4, 6))', self.source)
        self.assertIn('docs_lock_row.pack(fill="x", padx=14, pady=(0, 4))', self.source)
        self.assertIn('control_card.pack(fill="x", pady=(0, 4))', self.source)
        self.assertIn('row.pack(fill="x", padx=14, pady=4)', self.source)
        self.assertIn('button_spacer = ctk.CTkFrame(', self.source)
        self.assertIn('width=1,', self.source)
        self.assertIn('height=1,', self.source)
        self.assertIn('button_spacer.pack(side="left", fill="x", expand=True, padx=(8, 8))', self.source)
        self.assertIn('header_actions = ctk.CTkFrame(', self.source)
        self.assertIn('width=238,', self.source)
        self.assertIn('header_actions.pack(side="right", padx=(10, 0))', self.source)
        self.assertIn('header_actions.pack_propagate(False)', self.source)
        self.assertIn('result_column = ctk.CTkFrame(workspace_frame, fg_color="transparent", width=500)', self.source)
        self.assertIn('result_column.pack(side="left", fill="both", expand=True, padx=(0, 12))', self.source)
        self.assertIn("Messenger Docs Workspace", self.source)
        self.assertIn("작업 설정", self.source)
        self.assertIn("watch_folder_drop_hint", self.source)
        self.assertIn("라인 캐시 크기", self.source)
        self.assertIn("캐시 폴더 열기", self.source)
        self.assertIn("작업 결과 알림", self.source)
        self.assertIn("작업 결과 효과음", self.source)
        self.assertIn("Windows 자동 실행", self.source)
        self.assertIn("최근 추출 결과", self.source)
        self.assertIn("작업 로그", self.source)
        self.assertIn("로그 팝업", self.source)
        self.assertIn("placeholder_text=", self.source)
        self.assertIn("docs_target_status_var", self.source)
        self.assertIn("validate_positive_integer_input", self.source)

    def test_main_window_ui_keeps_docs_actions_and_primary_controls(self):
        self.assertIn('text="새 문서 만들기"', self.source)
        self.assertIn('text="기존 문서 주소 입력"', self.source)
        self.assertIn('text="문서 목록"', self.source)
        self.assertIn('text="문서 경로 확정"', self.source)
        self.assertIn('작업 결과 알림 표시', self.source)
        self.assertIn('작업 결과 효과음 재생', self.source)
        self.assertIn('text="미리보기 지우기"', self.source)
        self.assertIn("기본 창이 좁으면 '로그 팝업' 버튼으로 별도 창에서 볼 수 있습니다.", self.source)
        self.assertIn('text="감시 시작"', self.source)
        self.assertIn('text="감시 중지"', self.source)
        self.assertIn('text="Docs 웹에서 열기"', self.source)
        self.assertIn('text="폴더 열기"', self.source)
        self.assertIn('text="캐시 폴더 열기"', self.source)
        self.assertIn('text="검색"', self.source)
        self.assertIn('text="지우기"', self.source)
        self.assertIn("watch_folder_entry", self.source)
        self.assertIn('textvariable=state_vars["watch_folder_drop_hint"]', self.source)
        self.assertIn('text="Windows 로그인 시 자동으로 실행"', self.source)
        self.assertIn("CTkSwitch(", self.source)
        self.assertIn('textvariable=state_vars["autostart_hint"]', self.source)
        self.assertIn("height=34", self.source)
        self.assertIn("height=32", self.source)
        self.assertIn("height=168", self.source)
        self.assertIn("height=124", self.source)
        self.assertIn("width=480", self.source)
        self.assertIn("문서 ID", self.source)
        self.assertIn('"watch_folder_browse_button": watch_folder_browse_button', self.source)
        self.assertIn('"watch_folder_open_button": watch_folder_open_button', self.source)
        self.assertIn('"cache_folder_button": cache_folder_button', self.source)
        self.assertIn('"autostart_switch": autostart_switch', self.source)
        self.assertIn("advanced_filter_button = ctk.CTkButton(", self.source)
        self.assertIn("backup_restore_button = ctk.CTkButton(", self.source)
        self.assertIn('_attach_tooltip(', self.source)
        self.assertIn("전역 라인 캐시와 처리 상태 파일이 저장된 폴더를 Windows 탐색기에서 엽니다.", self.source)
        self.assertIn("현재 앱 메모리 사용량을 점검하고 가능한 정리 작업을 실행합니다.", self.source)
        self.assertIn("확장자 외에 정규식과 세부 필터 조건을 추가로 설정합니다.", self.source)
        self.assertIn("현재 계정에서 접근 가능한 Google Docs 목록을 불러와 작업 문서를 선택합니다.", self.source)
        self.assertIn("현재 입력된 문서를 작업 대상으로 고정해 감시 시작 전에 다시 바뀌지 않게 합니다.", self.source)
        self.assertIn("스위치를 바꾸면 Windows 시작프로그램 폴더의 자동 실행 상태가 바로 변경됩니다.", self.source)
        self.assertIn("작업 로그를 별도 창으로 열어 좁은 화면에서도 편하게 확인합니다.", self.source)
        self.assertIn("현재 설정을 백업 파일로 저장하거나 이전 백업 설정을 불러옵니다.", self.source)
        self.assertIn("화면에 표시된 로그만 지우며 저장된 로그 파일은 삭제하지 않습니다.", self.source)
        self.assertIn("현재 표시 중인 최근 추출 결과만 지우며 원본 기록과 문서 내용은 유지합니다.", self.source)


if __name__ == "__main__":
    unittest.main()
